location= "Asia/Omsk"   		#Временной пояс сервера
secret=false                    #Шифруем каналы передачи данных
#Описание параметров доступа к БД
[dataBase]
	host= "192.168.115.115"
	port= 5432
	user= "postgres"
	password= "162747"
	dbname= "agserv"
#Прием внешних данных
#Настройки сервера контроллеров
[commServer]
    id= 167						#ID сервера
	port= 2093					#Основной порт связи
    ipDevice="192.168.115.159"  #Адрес по которому ждем второй канал
    portDevice=2094
    debug=true
    ipDebug="192.168.115.159"   #Адрес для сообщений отладчика
    portDebug=2095
